#!/bin/sh

# lanscan pings all hosts in 192.168.1.* and, for each that replies, prints
# the host's name as reported by a DNS reverse lookup.
#
# I use it to answer the question "who's connected to my router?" because
# the router web UI sucks and only shows wirelessly connected hosts (I think).

pingable() {
    # $1: IP address of the host to ping

    # -q: quiet
    # -c 1: send one ping
    # -W 0.5: 0.5 second timeout per ping
    ping -q -c 1 -W 0.5 $1 >/dev/null 2>&1
}

try_ip() {
    # $1: IP address of the host to ping/lookup

    if pingable $1; then
        # +short: just the name (not the whole DNS record)
        # -x: reverse lookup (IP -> hostname)
        # sed: unqualify the name (e.g. mylaptop.isp.com -> mylaptop)
        echo $1 $(dig +short -x $1 | sed 's/\..*$//')
    fi
}

# Try the IPs in parallel, and then wait for them to finish.
for i in $(seq 255); do
    try_ip 192.168.1.$i &
done

wait
