#!/bin/sh

ss -nlt | awk '{print $4, $5}' | column -t

# e.g. 
#
#     $ ports
#     Local             Address:Port
#     127.0.0.53%lo:53  0.0.0.0:*
#     127.0.0.1:631     0.0.0.0:*
#     127.0.0.1:80      0.0.0.0:*
#     [::1]:631         [::]:*
#     [::1]:80          [::]:*


# alternative: sudo lsof -iTCP -sTCP:LISTEN -P -n

